config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  root "pages#index"

  get "simple", to: "pages#simple"
  get "no-router", to: "pages#no_router"

  # React Router needs a wildcard
  get "react-router(/*all)", to: "pages#index"

  resources :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :author
  validates_presence_of :text
end

app/models/git_commit_sha.rb
# Retrieves the current git commit SHA of the project
class GitCommitSha
  def self.current_sha
    @sha ||= retrieve_sha_from_file.presence || retrieve_sha_from_git
  end

  def self.current_sha=(sha)
    @sha = sha
  end

  def self.reset_current_sha
    self.current_sha = nil
  end

  # Assumes the git CLI is available. This is not the case in production on Heroku.
  def self.retrieve_sha_from_git
    `git rev-parse HEAD 2>/dev/null`.to_s.strip
  end

  # Assumes a .source_version file with SHA inside. A special Heroku buildpack creates this for us in production.
  def self.retrieve_sha_from_file
    expected_filepath = Rails.root.join(".source_version")
    File.exist?(expected_filepath) ? File.read(expected_filepath).to_s.strip : nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception,
                       if: proc { request.headers["X-Auth"] != "tutorial_secret" }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all.order("id DESC")
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:author, :text)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include ReactOnRails::Controller
  before_action :set_comments

  def index
    # NOTE: The below notes apply if you want to set the value of the props in the controller, as
    # compared to the view. However, it's more convenient to use Jbuilder from the view. See
    # app/views/pages/index.html.erb:20
    #
    #  <%= react_component('App', props: render(template: "/comments/index.json.jbuilder"),
    #     prerender: true) %>
    #
    #
    # NOTE: this could be an alternate syntax if you wanted to pass comments as a variable to a partial
    # @comments_json_sting = render_to_string(partial: "/comments/comments.json.jbuilder",
    #                                         locals: { comments: Comment.all }, format: :json)
    # NOTE: @comments is used by the render_to_string call
    # @comments_json_string = render_to_string("/comments/index.json.jbuilder")
    # NOTE: It's CRITICAL to call respond_to after calling render_to_string, or else Rails will
    # not render the HTML version of the index page properly. (not a problem if you do this in the view)
    # respond_to do |format|
    #   format.html
    # end

    redux_store("routerCommentsStore", props: comments_json_string)
    render_html
  end

  # Declaring no_router and simple to indicate we have views for them
  def no_router
    redux_store("commentsStore", props: comments_json_string)
    render_html
  end

  def simple
  end

  private

  def set_comments
    @comments = Comment.all.order("id DESC")
  end

  def comments_json_string
    render_to_string(template: "/comments/index.json.jbuilder",
                     locals: { comments: Comment.all }, format: :json)
  end

  def render_html
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def git_commit_sha
    GitCommitSha.current_sha
  end

  def git_commit_sha_short
    full_sha = git_commit_sha
    full_sha[-7..-1]
  end
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author, 'Your Name' %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :text, 'Say something using markdown...' %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit 'Post' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Using Classic Rails 4.2 "generate scaffold"</h1>
<hr/>

<p id="notice"><%= notice %></p>

<h2>Listing Comments</h2>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<div class="comment">
  <p id="notice"><%= notice %></p>

  <p class="js-comment-author">
    <strong>Author:</strong>
    <%= @comment.author %>
  </p>

  <p class="js-comment-text">
    <strong>Text:</strong>
    <%= @comment.text %>
  </p>
</div>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsReactTutorial</title>

  <%= env_stylesheet_link_tag(static: 'application_static',
                              hot: 'application_non_webpack',
                              media: 'all',
                              'data-turbolinks-track' => "reload")  %>

  <!-- These do not use turbolinks, so no data-turbolinks-track -->
  <!-- This is to load the hot assets. -->
  <%= env_javascript_include_tag(hot: ['http://localhost:3500/vendor-bundle.js',
                                       'http://localhost:3500/app-bundle.js']) %>

  <!-- These do use turbolinks -->
  <%= env_javascript_include_tag(static: 'application_static',
                                 hot: 'application_non_webpack',
                                 'data-turbolinks-track' => "reload") %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= react_component "NavigationBarApp" %>

<div class="container">
  <%= yield %>
</div>

<!-- This is a placeholder for ReactOnRails to know where to render the store props for
     client side hydration -->
<%= redux_store_hydration_data %>

</body>
</html>

app/views/pages/_header.html.erb
<p>Current Commit:
  <%= link_to git_commit_sha_short,
              "https://github.com/shakacode/react-webpack-rails-tutorial/commit/#{git_commit_sha}",
              id: "git-commit-sha" %>
</p>
<ul>
  <li>
    <%= link_to "ShakaCode", "http://www.shakacode.com"%>
    is doing Skype plus Slack/Github based coaching for
    <%= link_to "React on Rails", "https://github.com/shakacode/react_on_rails" %>.
    <b><%= link_to "Click here", "http://www.shakacode.com/work/index.html" %></b> for more information.
  </li>
  <li>
    If this work interests you and you're a developer or designer looking for full or part-time remote work: please
    visit <%= link_to "ShakaCode.com", "http://www.shakacode.com" %>,
    <%= link_to "click here",
                "http://forum.shakacode.com/t/railsonmaui-is-hiring-and-partnering-part-time-remote-is-ok/156/3" %>
    and
    <%= link_to "here",
                "http://forum.shakacode.com/t/railsonmaui-is-hiring-and-partnering-part-time-remote-is-ok/156/2" %>.
  </li>
  <li>
    Please see the
    <%= link_to "github.com/shakacode/react-webpack-rails-tutorial/README.md",
                "https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/README.md" %>
    for details of how this example site was built.
  </li>
  <li>
    Be sure to read our new article
    <%= link_to "The React on Rails Doctrine",
                "http://www.shakacode.com/2016/01/27/the-react-on-rails-doctrine.html" %>.
  </li>
  <li>
    See our React Native Client: 
    <%= link_to "shakacode/react-native-tutorial",
                "https://github.com/shakacode/react-native-tutorial" %>.
  </li>
</ul>
<hr/>

app/views/pages/index.html.erb
<h2>
  Featuring the <%= link_to "React on Rails gem", "https://github.com/shakacode/react_on_rails" %>
</h2>
<h3>Using <%= link_to "Ruby on Rails", "http://rubyonrails.org/" %> with
  <%= link_to "React", "http://facebook.github.io/react/" %> (Server rendering) +
  <%= link_to "Redux", "https://github.com/reactjs/redux" %> +
  <%= link_to "React Router", "https://github.com/reactjs/react-router" %> +
  <%= link_to "react-router-redux" , "https://github.com/reactjs/react-router-redux" %>
</h3>
<%= render "header" %>

<!--Note, pre-rendering set in /config/initializers/react_on_rails.rb -->
<%= react_component('RouterApp', id: "RouterApp-react-component-0") %>

app/views/pages/no_router.html.erb
<h2>Using React (Server rendering) + Redux + Rails Backend (using the
  <a href="https://github.com/shakacode/react_on_rails">react_on_rails gem</a>)</h2>
<%= render "header" %>

<!--Note, pre-rendering set in /config/initializers/react_on_rails.rb -->
<%= react_component('App') %>

app/views/pages/simple.html.erb
<h2>Using React (no Flux framework) + Rails Backend (with
  <a href="https://github.com/shakacode/react_on_rails">react_on_rails gem</a>)</h2>
<p>This example is much simpler than the one using React + Redux and is appropriate when:</p>
<ul>
  <li>No or minimal MVC</li>
  <li>No async necessary</li>
  <li>No server rendering</li>
  <li>No pre-population of props</li>
</ul>
<hr/>

<!-- This component is super simple! So no redux, no prerendering. -->
<%= react_component('SimpleCommentScreen', props: {}, prerender: false) %>